import assert from 'node:assert/strict';
import { before, after, test } from 'node:test';
import { createServer } from 'vite';
import { chromium } from 'playwright';
import { authAlias } from './authenticated.vite.mjs';

const A='00000000-0000-4000-8000-000000000001', B='00000000-0000-4000-8000-000000000002';
const account={account_id:'00000000-0000-4000-8000-000000000003',display_name:'Publishing account',platform:'instagram',organic_owner:null};
const another={account_id:'00000000-0000-4000-8000-000000000004',display_name:'Second account',platform:'facebook',organic_owner:null};
const item=(analyzed)=>({library_item_id:'00000000-0000-4000-8000-000000000005',display_title:'Existing video',platform:'instagram',content_type:'reel',published_at:'2026-10-01T00:00:00Z',analysis_state:analyzed?'completed':'discovered',analyzed});
const free=(changes={})=>({plan:'free',effective_plan:'free',subscription_status:null,cancel_at_period_end:false,grace_until:null,entitlements:{organic_account_limit:1,analysis_limit:3,idea_generation_limit:5},usage:{analyses:0,idea_generations:0},period:{starts_at:'2026-10-01T00:00:00Z',ends_at:'2026-11-01T00:00:00Z'},can_manage_billing:true,...changes});
const pro=(changes={})=>free({plan:'pro',effective_plan:'pro',subscription_status:'active',entitlements:{organic_account_limit:5,analysis_limit:50,idea_generation_limit:150},...changes});
let server,browser,origin;
before(async()=>{server=await createServer({resolve:{alias:authAlias},server:{host:'127.0.0.1',port:0},logLevel:'error'});await server.listen();origin=server.resolvedUrls.local[0];browser=await chromium.launch();});
after(async()=>{await browser?.close();await server?.close();});
async function fixture({bill=free(),width=1440,role='owner',second=false,createLimit=false,linkLimit=false,analysisLimit=false,ideaLimit=false,hasContent=false,analyzed=false,selected=A,returnKind=null,delayBilling=false,billingStatus=200,delayDestination=false}={}){
 const context=await browser.newContext({viewport:{width,height:900}});
 await context.addInitScript(({selected,returnKind})=>{window.__authMock={session:{access_token:'test-token-a',user:{id:'10000000-0000-4000-8000-000000000001',email:'a@example.com'}}};localStorage.setItem('video-analyzer.active-company-id',selected);if(returnKind)sessionStorage.setItem('contentmetric.billing-return',JSON.stringify({kind:returnKind,companyId:selected,at:Date.now()}));},{selected,returnKind});
 let current=bill,delayed=delayBilling,destination=null;const calls=[],errors=[];
 const companies=[{company_id:A,name:'Alpha',role,archived:false,accounts:[account]},...(second?[{company_id:B,name:'Beta',role:'owner',archived:false,accounts:[]}]:[])];
 await context.route('**/api/**',async route=>{
  const req=route.request(),path=new URL(req.url()).pathname,method=req.method();calls.push({path,method,authorization:req.headers().authorization});
  if(path==='/api/me/companies')return route.fulfill({json:{companies:companies.map(c=>({id:c.company_id,archived_at:null}))}});
  if(path==='/api/companies')return method==='POST'?route.fulfill(createLimit?{status:402,json:{detail:{code:'free_workspace_limit_reached'}}}:{json:companies[0]}):route.fulfill({json:{companies}});
  if(path==='/api/meta/test')return route.fulfill({json:{connected:linkLimit}});
  if(path==='/api/me/onboarding')return route.fulfill({json:{company_id:A,welcome_seen:true,skipped:false,progress:100,complete:true,next_step:null,steps:{workspace:true,meta:true,account:true,analysis:true,idea:true}}});
  if(path.endsWith('/billing')){if(delayed&&path.includes(`/${A}/`))return new Promise(resolve=>{delayed={route,resolve};});return route.fulfill(billingStatus===200?{json:path.includes(`/${B}/`)?free({usage:{analyses:1,idea_generations:2}}):current}:{status:billingStatus,json:{detail:'PRIVATE_BILLING_ERROR'}});}
  if(path.endsWith('/billing/checkout')){if(delayDestination)return new Promise(resolve=>{destination={route,resolve};});return route.fulfill({json:{url:'https://checkout.stripe.com/c/pay/test'}});}
  if(path.endsWith('/billing/portal'))return route.fulfill({json:{url:'https://billing.stripe.com/p/session/test'}});
  if(path==='/api/meta/accounts')return route.fulfill({json:{accounts:[account,another]}});
  if(path.endsWith(`/accounts/${another.account_id}`))return route.fulfill(linkLimit?{status:402,json:{detail:{code:'organic_account_limit_reached'}}}:{json:companies[0]});
  if(path.endsWith('/content/analyze'))return route.fulfill(analysisLimit?{status:402,json:{detail:{code:'analysis_limit_reached'}}}:{json:{ok:true}});
  if(path.endsWith('/recommendations'))return route.fulfill(ideaLimit?{status:402,json:{detail:{code:'idea_generation_limit_reached'}}}:{json:{}});
  if(path.endsWith('/content'))return route.fulfill({json:{items:hasContent?[item(analyzed)]:[],next_offset:null}});
  if(path.endsWith('/ideas'))return route.fulfill({json:{items:[],next_cursor:null}});
  return route.fulfill({json:{}});
 });
 await context.route('https://checkout.stripe.com/**',r=>r.fulfill({body:'<title>Stripe Checkout</title>'}));
 await context.route('https://billing.stripe.com/**',r=>r.fulfill({body:'<title>Stripe Portal</title>'}));
 const page=await context.newPage();page.setDefaultTimeout(6000);page.on('pageerror',e=>errors.push(e.message));await page.goto(`${origin}#settings`);await page.getByRole('heading',{name:'Settings',exact:true}).waitFor();
 return {page,context,calls,setBilling(value){current=value},delay(){delayed=true},release(){if(delayed?.route){delayed.resolve(delayed.route.fulfill({json:current}));delayed=null;}},releaseDestination(){if(destination){destination.resolve(destination.route.fulfill({json:{url:'https://checkout.stripe.com/c/pay/test'}}));destination=null;}},async close(){await context.close();assert.deepEqual(errors,[])}};
}
test('Free, zero and partial usage, period, comparison and owner controls',async()=>{const f=await fixture({bill:free({usage:{analyses:2,idea_generations:3}})});try{const p=f.page;await p.getByRole('heading',{name:'Billing'}).waitFor();await p.getByText('2 of 3 used').waitFor();await p.getByText('3 of 5 used').waitFor();await p.getByText('Pro — €19/month per workspace').waitFor();await p.getByRole('button',{name:'Upgrade to Pro'}).waitFor();assert.match(await p.locator('.billing-section').innerText(),/1 November 2026/);assert.equal(f.calls.some(c=>c.path.endsWith('/billing')&&c.authorization==='Bearer test-token-a'),true);}finally{await f.close();}});
test('Pro, cancellation, grace and effective Free states follow backend',async()=>{for(const [bill,text]of [[pro({usage:{analyses:18,idea_generations:42}}),'18 of 50 used'],[pro({cancel_at_period_end:true}),'scheduled to end'],[pro({subscription_status:'past_due',grace_until:'2026-10-17T00:00:00Z'}),'Payment needs attention'],[free({plan:'pro',subscription_status:'unpaid'}),'Subscription needs attention']]){const f=await fixture({bill});try{await f.page.getByText(text,{exact:false}).first().waitFor();if(bill.effective_plan==='free')assert.match(await f.page.locator('.billing-plan').innerText(),/Free/);else await f.page.getByRole('button',{name:'Manage subscription'}).waitFor();}finally{await f.close();}}});
test('member sees plan and usage without management actions',async()=>{const f=await fixture({role:'member',bill:free({can_manage_billing:false})});try{await f.page.getByText('0 of 3 used').waitFor();assert.equal(await f.page.getByRole('button',{name:'Upgrade to Pro'}).count(),0);assert.equal(await f.page.getByRole('button',{name:'Manage subscription'}).count(),0);}finally{await f.close();}});
test('Checkout and Portal use authenticated POST and hosted URL',async()=>{for(const [bill,button,ending,host]of [[free(),'Upgrade to Pro','checkout','checkout.stripe.com'],[pro(),'Manage subscription','portal','billing.stripe.com']]){const f=await fixture({bill});try{await f.page.getByRole('button',{name:button}).click();await f.page.waitForURL(url=>url.hostname===host);assert.equal(f.calls.filter(c=>c.path.endsWith(`/billing/${ending}`)&&c.method==='POST'&&c.authorization==='Bearer test-token-a').length,1);}finally{await f.close();}}});
test('leaving Settings cancels a pending hosted redirect',async()=>{const f=await fixture({delayDestination:true});try{await f.page.getByRole('button',{name:'Upgrade to Pro'}).click();await f.page.getByRole('navigation',{name:'Primary'}).getByRole('link',{name:'Overview'}).click();f.releaseDestination();await f.page.waitForTimeout(150);assert.equal(new URL(f.page.url()).host,new URL(origin).host);}finally{await f.close();}});
test('return refresh is bounded and never grants Pro locally',async()=>{for(const kind of ['checkout','portal']){const f=await fixture({returnKind:kind});try{await f.page.getByText('Updating your subscription…',{exact:false}).waitFor();await f.page.getByText('Free',{exact:true}).first().waitFor();await f.page.waitForTimeout(kind==='checkout'?6800:2100);assert.ok(f.calls.filter(c=>c.path.endsWith('/billing')).length<=5);assert.match(await f.page.locator('.billing-plan').innerText(),/Free/);}finally{await f.close();}}});
test('workspace 402 has a Billing path and no raw error',async()=>{const f=await fixture({createLimit:true});try{await f.page.getByLabel('New company name').fill('New');await f.page.getByRole('button',{name:'Create company'}).click();await f.page.getByText('Your Free plan includes one workspace.').waitFor();assert.equal((await f.page.locator('body').innerText()).includes('free_workspace_limit_reached'),false);}finally{await f.close();}});
test('organic account 402 leaves linked accounts visible and unlink available',async()=>{const f=await fixture({linkLimit:true});try{const p=f.page;await p.getByRole('checkbox',{name:'Second account'}).click();await p.getByText('Publishing account limit reached.').waitFor();assert.equal(await p.getByRole('checkbox',{name:'Publishing account'}).isChecked(),true);assert.equal(await p.getByRole('checkbox',{name:'Publishing account'}).isEnabled(),true);assert.equal(f.calls.some(c=>c.path.endsWith(`/accounts/${another.account_id}`)&&c.method==='PUT'),true);}finally{await f.close();}});
test('analysis 402 preserves content and shows Free upgrade',async()=>{const f=await fixture({hasContent:true,analysisLimit:true,bill:free({usage:{analyses:3,idea_generations:0}})});try{const p=f.page;await p.getByRole('navigation',{name:'Primary'}).getByRole('link',{name:'Content'}).click();await p.getByRole('button',{name:'Analyze',exact:true}).click();await p.getByText("You've used this period's analysis allowance.").first().waitFor();await p.getByText('Existing video').waitFor();await p.getByText('3 of 3 analyses used').first().waitFor();assert.ok(f.calls.filter(c=>c.path.endsWith('/billing')).length>=2);}finally{await f.close();}});
test('Pro analysis limit offers reset rather than upgrade',async()=>{const f=await fixture({hasContent:true,bill:pro({usage:{analyses:50,idea_generations:0}})});try{await f.page.getByRole('navigation',{name:'Primary'}).getByRole('link',{name:'Content'}).click();await f.page.getByText("You've used this period's analysis allowance.").waitFor();await f.page.getByText('Resets 1 November 2026.').waitFor();assert.equal(await f.page.getByRole('button',{name:'Upgrade to Pro'}).count(),0);}finally{await f.close();}});
test('idea 402 preserves sources and offers Free upgrade',async()=>{const f=await fixture({hasContent:true,analyzed:true,ideaLimit:true,bill:free({usage:{analyses:1,idea_generations:5}})});try{const p=f.page;await p.getByRole('navigation',{name:'Primary'}).getByRole('link',{name:'Generate'}).click();await p.getByRole('button',{name:'Generate idea'}).click();await p.getByText("You've used this period's idea allowance.").first().waitFor();await p.locator('.generate-workspace').getByText('Using 1 source item',{exact:false}).waitFor();await p.getByText('5 of 5 ideas used').first().waitFor();}finally{await f.close();}});
test('Pro idea limit shows reset and keeps Generate readable',async()=>{const f=await fixture({hasContent:true,analyzed:true,bill:pro({usage:{analyses:1,idea_generations:150}})});try{await f.page.getByRole('navigation',{name:'Primary'}).getByRole('link',{name:'Generate'}).click();await f.page.getByText("You've used this period's idea allowance.").waitFor();await f.page.getByText('Resets 1 November 2026.').waitFor();assert.equal(await f.page.getByRole('button',{name:'Upgrade to Pro'}).count(),0);}finally{await f.close();}});
test('switch clears previous billing and stale A response cannot overwrite B',async()=>{const f=await fixture({second:true,delayBilling:true,bill:pro({usage:{analyses:18,idea_generations:42}})});try{const p=f.page;await p.getByRole('navigation',{name:'Company'}).getByRole('button').first().click();await p.getByRole('navigation',{name:'Company'}).getByRole('button',{name:'Beta'}).click();await p.getByRole('navigation',{name:'Primary'}).getByRole('link',{name:'Settings'}).click();await p.getByText('1 of 3 used').waitFor();f.release();await p.waitForTimeout(200);assert.equal((await p.locator('.billing-section').innerText()).includes('18 of 50 used'),false);}finally{await f.close();}});
test('billing 404 stays local while Ideas remains readable',async()=>{const f=await fixture({billingStatus:404});try{await f.page.getByText('This workspace is unavailable to your account.').waitFor();await f.page.getByRole('navigation',{name:'Primary'}).getByRole('link',{name:'Ideas'}).click();await f.page.getByRole('heading',{name:'Ideas',exact:true}).waitFor();assert.equal((await f.page.locator('body').innerText()).includes('PRIVATE_BILLING_ERROR'),false);}finally{await f.close();}});
for(const width of [1440,1024,768,390,320])test(`Billing fits ${width}px and keyboard works`,async()=>{const f=await fixture({width});try{const p=f.page;await p.getByText('0 of 3 used').waitFor();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.getByRole('navigation',{name:'Settings sections'}).getByRole('button',{name:'Billing'}).focus();await p.keyboard.press('Enter');assert.equal(await p.locator('#settings-billing').evaluate(el=>document.activeElement===el),true);assert.equal(await p.locator('vite-error-overlay').count(),0);}finally{await f.close();}});
