import assert from 'node:assert/strict';
import { test, before, after } from 'node:test';
import { createServer } from 'vite';
import { chromium } from 'playwright';
import { authOnlyAlias } from './authenticated.vite.mjs';

const A='00000000-0000-4000-8000-000000000001', B='00000000-0000-4000-8000-000000000002';
const UA='10000000-0000-4000-8000-000000000001', UB='10000000-0000-4000-8000-000000000002';
const flags=(done=[])=>Object.fromEntries(['workspace','meta','account','analysis','idea'].map(key=>[key,done.includes(key)]));
const status=(override={})=>({company_id:null,welcome_seen:false,skipped:false,progress:0,complete:false,next_step:'workspace',steps:flags(),...override});
let server,browser,origin;
before(async()=>{server=await createServer({resolve:{alias:authOnlyAlias},server:{host:'127.0.0.1',port:0},logLevel:'error'});await server.listen();origin=server.resolvedUrls.local[0];browser=await chromium.launch();});
after(async()=>{await browser?.close();await server?.close();});
async function fixture({state=status(),stateB=null,companies=[],selected=null,width=1440,fail=null,refreshInvalid=false,expectApp=true}={}){
 const context=await browser.newContext({viewport:{width,height:900}});
 await context.addInitScript(({selected,refreshInvalid})=>{window.__authMock={session:{access_token:'test-token-a',user:{id:'10000000-0000-4000-8000-000000000001',email:'a@example.com'}},refreshInvalid};if(selected)localStorage.setItem('video-analyzer.active-company-id',selected);},{selected,refreshInvalid});
 const calls=[],errors=[];let current=state,records=[...companies],failure=fail;
 await context.route('**/api/**',route=>{
  const request=route.request(),path=new URL(request.url()).pathname,method=request.method(),bob=request.headers().authorization==='Bearer test-token-b';calls.push({path,method,headers:request.headers(),body:request.postDataJSON()});
  if(path==='/api/me/companies')return route.fulfill({json:{companies:(bob?[]:records).map(c=>({id:c.company_id,archived_at:c.archived?new Date().toISOString():null}))}});
  if(path==='/api/me/onboarding')return failure?route.fulfill({status:failure,json:{detail:'PRIVATE_DB_ERROR'}}):route.fulfill({json:bob&&stateB?stateB:current});
  if(path==='/api/me/onboarding/welcome'){current={...current,welcome_seen:true};return route.fulfill({json:{}});}
  if(path==='/api/me/onboarding/skip'){current={...current,skipped:true};return route.fulfill({json:{}});}
  if(path==='/api/me/onboarding/company'){current={...current,company_id:request.postDataJSON().company_id,steps:{...current.steps,workspace:true},progress:20,next_step:'meta'};return route.fulfill({json:{}});}
  if(path==='/api/companies'&&method==='POST'){const c={company_id:B,name:request.postDataJSON().name,role:'owner',archived:false,accounts:[]};records.push(c);return route.fulfill({json:c});}
  if(path==='/api/companies')return route.fulfill({json:{companies:records}});
  if(path==='/api/meta/test')return route.fulfill({json:{connected:false}});
  if(path==='/api/meta/connect')return route.fulfill({json:{authorization_url:'https://www.facebook.com/dialog/oauth?test=1'}});
  if(path.endsWith('/content'))return route.fulfill({json:{items:[],next_offset:null}});
  if(path.endsWith('/ideas'))return route.fulfill({json:{items:[],next_cursor:null}});
  return route.fulfill({json:{accounts:[],connected:false}});
 });
 const page=await context.newPage();page.setDefaultTimeout(6000);page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin);if(expectApp)await page.getByRole('heading',{level:1,name:'Overview'}).waitFor();
 return {page,calls,context,get state(){return current},setState(value){current=value},setFail(value){failure=value},async close(){assert.deepEqual(errors,[]);await context.close()}};
}
const heading=(page,name)=>page.getByRole('heading',{name,exact:true});
test('new user sees welcome, starts guided setup and skips to persistent reminder',async()=>{const f=await fixture();try{const p=f.page;await heading(p,'Welcome to ContentMetric').waitFor();assert.equal(await p.locator('[role=progressbar]').count(),0);await p.getByRole('button',{name:'Start setup'}).click();await heading(p,'Set up ContentMetric').waitFor();assert.equal(f.calls.filter(c=>c.path.endsWith('/welcome')).length,1);await p.getByRole('button',{name:'Skip for now'}).click();await heading(p,'Finish setting up ContentMetric').waitFor();assert.equal(f.state.complete,false);assert.equal(f.state.skipped,true);await p.getByRole('button',{name:/Continue setup/}).click();await heading(p,'Set up ContentMetric').waitFor();}finally{await f.close();}});
test('skip from welcome posts welcome before skip and preserves app navigation',async()=>{const f=await fixture();try{const p=f.page;await heading(p,'Welcome to ContentMetric').waitFor();await p.getByRole('button',{name:'Skip for now'}).click();await heading(p,'Finish setting up ContentMetric').waitFor();const paths=f.calls.map(c=>c.path);assert.ok(paths.indexOf('/api/me/onboarding/welcome')<paths.indexOf('/api/me/onboarding/skip'));await p.getByRole('navigation',{name:'Primary'}).getByRole('link',{name:'Content'}).click();await heading(p,'Content').waitFor();}finally{await f.close();}});
test('existing partial user without onboarding row sees normal app and a setup reminder',async()=>{const f=await fixture({state:status({company_id:A,progress:20,next_step:'meta',steps:flags(['workspace'])}),companies:[{company_id:A,name:'Existing',role:'owner',archived:false,accounts:[]}],selected:A});try{await heading(f.page,'Finish setting up ContentMetric').waitFor();assert.equal(await heading(f.page,'Welcome to ContentMetric').count(),0);assert.equal(await f.page.getByRole('progressbar').getAttribute('aria-valuenow'),'20');assert.equal(f.calls.some(c=>c.path.endsWith('/welcome')),false);}finally{await f.close();}});
test('company creation uses Settings behavior then persists onboarding company',async()=>{const f=await fixture({state:status({welcome_seen:true})});try{const p=f.page;await p.getByRole('button',{name:/Continue setup/}).click();await p.getByRole('button',{name:'Create workspace'}).click();await heading(p,'Settings').waitFor();await p.getByLabel('New company name').fill('New workspace');await p.getByRole('button',{name:'Create company'}).click();await heading(p,'Overview').waitFor();await p.waitForFunction(()=>document.body.textContent.includes('20% complete'));assert.equal(f.state.company_id,B);assert.ok(f.calls.some(c=>c.path==='/api/companies'&&c.method==='POST'));assert.ok(f.calls.some(c=>c.path==='/api/me/onboarding/company'&&c.body.company_id===B));}finally{await f.close();}});
test('existing companies require explicit onboarding choice and normal switch does not rewrite it',async()=>{const companies=[{company_id:A,name:'Alpha',role:'owner',archived:false,accounts:[]},{company_id:B,name:'Beta',role:'owner',archived:false,accounts:[]}];const f=await fixture({state:status({welcome_seen:true}),companies,selected:A});try{const p=f.page;await p.getByRole('button',{name:/Continue setup/}).click();await p.getByLabel('Choose a company for setup').selectOption(B);await p.getByRole('button',{name:'Use for setup'}).click();await p.getByText('Setup workspace:').waitFor();assert.equal(f.state.company_id,B);await p.getByRole('navigation',{name:'Company'}).getByRole('button').first().click();await p.getByRole('navigation',{name:'Company'}).getByRole('button',{name:'Beta'}).click();assert.equal(f.calls.filter(c=>c.path==='/api/me/onboarding/company').length,1);}finally{await f.close();}});
for(const progress of [20,40,60,80,100])test(`backend ${progress}% renders authoritative progress`,async()=>{const count=progress/20,done=['workspace','meta','account','analysis','idea'].slice(0,count);const f=await fixture({state:status({company_id:A,welcome_seen:true,progress,complete:progress===100,next_step:progress===100?null:['workspace','meta','account','analysis','idea'][count],steps:flags(done)}),companies:[{company_id:A,name:'Alpha',role:'owner',archived:false,accounts:[]}],selected:A});try{if(progress<100){await heading(f.page,'Finish setting up ContentMetric').waitFor();assert.equal(await f.page.getByRole('progressbar').getAttribute('aria-valuenow'),String(progress));}else{assert.equal(await heading(f.page,'Welcome to ContentMetric').count(),0);assert.equal(await heading(f.page,'Finish setting up ContentMetric').count(),0);}}finally{await f.close();}});
test('earlier incomplete step remains recommended even with later completed flags',async()=>{const f=await fixture({state:status({company_id:A,welcome_seen:true,progress:80,next_step:'meta',steps:flags(['workspace','account','analysis','idea'])}),companies:[{company_id:A,name:'Alpha',role:'owner',archived:false,accounts:[]}],selected:A});try{await f.page.getByRole('button',{name:/Continue setup/}).click();await heading(f.page,'Connect Meta').waitFor();assert.equal(await f.page.getByRole('progressbar').getAttribute('aria-valuenow'),'80');}finally{await f.close();}});
test('link, analysis and idea actions navigate into existing workflows',async()=>{const c=[{company_id:A,name:'Alpha',role:'owner',archived:false,accounts:[]}];for(const [step,label,destination]of [['account','Link Instagram or Facebook','Settings'],['analysis','Analyze your first content','Content'],['idea','Generate your first idea','Generate']]){const f=await fixture({state:status({company_id:A,welcome_seen:true,progress:60,next_step:step,steps:flags(['workspace','meta'])}),companies:c,selected:A});try{await f.page.getByRole('button',{name:/Continue setup/}).click();await f.page.getByRole('button',{name:label}).click();await heading(f.page,destination).waitFor();assert.ok(f.calls.filter(x=>x.path==='/api/me/onboarding').length>=2);}finally{await f.close();}}});
test('completion appears after backend refresh and disappears after leaving',async()=>{const f=await fixture({state:status({company_id:A,welcome_seen:true,progress:80,next_step:'idea',steps:flags(['workspace','meta','account','analysis'])}),companies:[{company_id:A,name:'Alpha',role:'owner',archived:false,accounts:[]}],selected:A});try{const p=f.page;await p.getByRole('button',{name:/Continue setup/}).click();f.setState(status({company_id:A,welcome_seen:true,progress:100,complete:true,next_step:null,steps:flags(['workspace','meta','account','analysis','idea'])}));await p.getByRole('button',{name:'Refresh progress'}).click();await heading(p,"You're ready to go").waitFor();await p.getByRole('button',{name:'Go to Overview'}).click();assert.equal(await heading(p,'Finish setting up ContentMetric').count(),0);}finally{await f.close();}});
test('backend errors show safe retry and 403 retains user',async()=>{const f=await fixture({fail:503});try{const p=f.page;await p.getByRole('button',{name:'Retry setup'}).waitFor();assert.doesNotMatch(await p.locator('body').innerText(),/PRIVATE_DB_ERROR/);f.setFail(null);await p.getByRole('button',{name:'Retry setup'}).click();await heading(p,'Welcome to ContentMetric').waitFor();f.setFail(403);await p.reload();await p.getByRole('button',{name:'Retry setup'}).waitFor();assert.equal(await p.getByRole('button',{name:'Sign out'}).count(),1);}finally{await f.close();}});
test('onboarding 401 follows V6 session expiry handling',async()=>{const f=await fixture({fail:401,refreshInvalid:true,expectApp:false});try{await heading(f.page,'Welcome back').waitFor();assert.equal(await heading(f.page,'Welcome to ContentMetric').count(),0);assert.ok(f.calls.some(c=>c.path==='/api/me/onboarding'&&c.headers.authorization==='Bearer test-token-a'));}finally{await f.close();}});
test('Meta step calls authenticated V6 JSON initiation',async()=>{const f=await fixture({state:status({company_id:A,welcome_seen:true,progress:20,next_step:'meta',steps:flags(['workspace'])}),companies:[{company_id:A,name:'Alpha',role:'owner',archived:false,accounts:[]}],selected:A});try{const p=f.page;await p.getByRole('button',{name:/Continue setup/}).click();const popup=f.context.waitForEvent('page');const response=p.waitForResponse(r=>r.url().includes('/api/meta/connect?response_mode=json'));await p.getByRole('button',{name:'Connect Meta'}).click();await popup;await response;const call=f.calls.find(c=>c.path==='/api/meta/connect');assert.equal(call.headers.authorization,'Bearer test-token-a');assert.equal(call.method,'GET');}finally{await f.close();}});
test('logout and identity change never retain another user setup state',async()=>{const f=await fixture({state:status({company_id:A,welcome_seen:true,progress:60,next_step:'analysis',steps:flags(['workspace','meta','account'])}),stateB:status({welcome_seen:true,progress:0}),companies:[{company_id:A,name:'Alice private workspace',role:'owner',archived:false,accounts:[]}],selected:A});try{const p=f.page;await heading(p,'Finish setting up ContentMetric').waitFor();await p.evaluate(()=>window.__changeAuth({access_token:'test-token-b',user:{id:'10000000-0000-4000-8000-000000000002',email:'b@example.com'}}));await p.getByText('b@example.com').waitFor();await p.getByRole('progressbar').waitFor();assert.equal(await p.getByRole('progressbar').getAttribute('aria-valuenow'),'0');assert.doesNotMatch(await p.locator('body').innerText(),/Alice private workspace|60% complete/);await p.getByRole('button',{name:'Sign out'}).click();await heading(p,'Welcome back').waitFor();assert.equal(await p.getByRole('progressbar').count(),0);}finally{await f.close();}});
test('missing setup company offers explicit recovery and mobile reminder fits',async()=>{const f=await fixture({state:status({company_id:A,welcome_seen:true,progress:40,next_step:'account',steps:flags(['workspace','meta'])}),companies:[{company_id:B,name:'Available',role:'owner',archived:false,accounts:[]}],selected:B,width:320});try{const p=f.page;await heading(p,'Finish setting up ContentMetric').waitFor();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.getByRole('button',{name:/Continue setup/}).click();await p.getByRole('alert').getByText(/setup company is unavailable/).waitFor();await p.getByLabel('Choose a company for setup').selectOption(B);await p.getByRole('button',{name:'Use for setup'}).click();assert.equal(f.state.company_id,B);}finally{await f.close();}});
for(const width of [1440,1024,768,390,320])test(`setup fits ${width}px and keyboard focus is visible`,async()=>{const f=await fixture({width});try{const p=f.page;await heading(p,'Welcome to ContentMetric').waitFor();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.getByRole('button',{name:'Start setup'}).focus();assert.equal(await p.evaluate(()=>getComputedStyle(document.activeElement).outlineStyle),'solid');await p.keyboard.press('Enter');await heading(p,'Set up ContentMetric').waitFor();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}finally{await f.close();}});
